### ISSUE TITLE
[BUG] build fail

### ISSUE THREAD

**Issue by dongfengweixiao** [dahliaOS/terminal#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

flutter 3.10.1

ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:45:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> get iterator;
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:49:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> get reverseIterator;
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:58:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> fromIterator(V anchor,
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:742:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> get iterator => _AvlTreeIterator._(this);
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:746:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> get reverseIterator =>
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:751:3: Error: Type 'BidirectionalIterator' not found.
ERROR:   BidirectionalIterator<V> fromIterator(V anchor,
ERROR:   ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/quiver-3.1.0/lib/src/collection/treeset.dart:894:38: Error: Type 'BidirectionalIterator' not found.
ERROR: class _AvlTreeIterator<V> implements BidirectionalIterator<V> {
ERROR:                                      ^^^^^^^^^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/google_fonts-3.0.1/lib/src/google_fonts_base.dart:14:1: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
ERROR: import 'asset_manifest.dart';
ERROR: ^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/git/xterm-5d4bd82cc4b288a21165255f273bf0421fa5f269/lib/src/ui/custom_text_edit.dart:54:7: Error: The non-abstract class 'CustomTextEditState' is missing implementations for these members:
ERROR:  - TextInputClient.insertContent
ERROR: Try to either
ERROR:  - provide an implementation,
ERROR:  - inherit an implementation from a superclass or mixin,
ERROR:  - mark the class as abstract, or
ERROR:  - provide a 'noSuchMethod' implementation.
ERROR: class CustomTextEditState extends State<CustomTextEdit> implements TextInputClient {
ERROR:       ^^^^^^^^^^^^^^^^^^^
ERROR: /opt/flutter/packages/flutter/lib/src/services/text_input.dart:1117:8: Context: 'TextInputClient.insertContent' is defined here.
ERROR:   void insertContent(KeyboardInsertedContent content) {}
ERROR:        ^^^^^^^^^^^^^
ERROR: ../../../../../.pub-cache/hosted/pub.dev/google_fonts-3.0.1/lib/src/google_fonts_base.dart:32:31: Error: 'AssetManifest' is imported from both 'package:flutter/src/services/asset_manifest.dart' and 'package:google_fonts/src/asset_manifest.dart'.
ERROR: AssetManifest assetManifest = AssetManifest();
ERROR:                               ^^^^^^^^^^^^^
ERROR: Target kernel_snapshot failed: Exception
Building Linux application...                                           
Build process failed

### Environment (values that do not apply assign with "N/A")

```markdown
- OS: archlinux
- Device: x86_64
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whiskeyPeak** [comment]
Hey thanks for the report! This is happening because we're depending on an older version of xterm. Will bump the dependency
